server:
  host: 0.0.0.0
  port: 8000
  use_ngrok: false
  use_auth: false
  auth_username: user
  auth_password: password
  log_file_path: logs/tts_server.log
  log_file_max_size_mb: 10
  log_file_backup_count: 5
model:
  repo_id: ResembleAI/chatterbox
tts_engine:
  device: mps
  predefined_voices_path: voices
  reference_audio_path: reference_audio
  default_voice_id: default_sample.wav
paths:
  model_cache: model_cache
  output: outputs
generation_defaults:
  temperature: 0.8
  exaggeration: 0.5
  cfg_weight: 0.5
  seed: 0
  speed_factor: 1.0
  language: en
audio_output:
  format: wav
  sample_rate: 24000
  max_reference_duration_sec: 30
ui_state:
  last_text: 'The solar system consists of the Sun and the astronomical objects gravitationally
    bound in orbit around it.

    Mars, often called the Red Planet, is the fourth planet from the Sun. It is a
    terrestrial planet with a thin atmosphere, having surface features reminiscent
    both of the impact craters of the Moon and the volcanoes, valleys, deserts, and
    polar ice caps of Earth.

    '
  last_voice_mode: clone
  last_predefined_voice: Axel.wav
  last_reference_file: nick_podel.wav
  last_seed: 0
  last_chunk_size: 120
  last_split_text_enabled: true
  hide_chunk_warning: false
  hide_generation_warning: true
  theme: light
ui:
  title: Chatterbox TTS Server
  show_language_select: true
  max_predefined_voices_in_dropdown: 20
debug:
  save_intermediate_audio: false
